### ISSUE TITLE
使用Git Bash时遇到的问题

### ISSUE THREAD

**Issue by Jiayze** [ANA-Training/student0#1]
我在练习使用git时，git bash意外关闭（不知道什么原因）
重新打开git bash后，按开始的方式操作，但指令无法运行，提示存在另一个git进程
![屏幕截图 2023-09-11 155405](https://github.com/ANA-Training/student0/assets/144600900/3e0647c6-6ed4-4e3a-a7cc-f7b1ba8647af)
请问应该如何解决

**Comment by abdtyx** [comment]
This post might be helpful: https://stackoverflow.com/questions/38004148/another-git-process-seems-to-be-running-in-this-repository
![截图 2023-09-11 20-29-50](https://github.com/ANA-Training/student0/assets/76111519/b262bd5e-57b8-4d0a-9f47-3d31fbdde7fe)
I noticed that you just came across a problem related with critical resources. As you can see, Git uses a lock to protect the critical resources. We'll be talking about the locks in the second lecture.
